### ISSUE TITLE
mvn -Pdeveloper -pl developer -Ddeploydb

### ISSUE THREAD

**Issue by bickrombishsass** [shapeblue/hackerbook#3]
_SQL exception in trying initDB: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'identified by 'cloud'' at line 1_

Is there anyone who is getting the same error while deploying ?

**Comment by DaanHoogland** [comment]
Can you give the versions of your db/os/mvn/java/etcetera, @bickrombishsass ? I've seen many like these and a lot of them are to do with for instance line endings or mysql versions, but there is not enough infromation here to give a satisfying answer.

**Comment by rhtyd** [comment]
@bickrombishsass were you able to resolve this issue? Do you've MySQL server running with root user (default password blank for code to work out of the box)?

**Comment by bickrombishsass** [comment]
Yes.

**Comment by rhtyd** [comment]
Closing on the remark

**Comment by bickrombishsass** [comment]
Ok thank you. The issue is solved. I can log into now.
